// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AllSubCategories: typeof import('./src/views/category/components/AllSubCategories.vue')['default']
    FreshGoods: typeof import('./src/views/home/component/FreshGoods.vue')['default']
    GoodsItem: typeof import('./src/views/category/components/GoodsItem.vue')['default']
    GoodsList: typeof import('./src/views/category/components/GoodsList.vue')['default']
    HomeBanner: typeof import('./src/views/home/component/HomeBanner.vue')['default']
    HomeCategory: typeof import('./src/views/home/component/HomeCategory.vue')['default']
    HomeGoods: typeof import('./src/views/home/component/HomeGoods.vue')['default']
    HomePage: typeof import('./src/views/home/HomePage.vue')['default']
    HomePanel: typeof import('./src/views/home/component/HomePanel.vue')['default']
    HomeSkeleton: typeof import('./src/views/home/component/HomeSkeleton.vue')['default']
    HomeSpecial: typeof import('./src/views/home/component/HomeSpecial.vue')['default']
    HotBrands: typeof import('./src/views/home/component/HotBrands.vue')['default']
    HotRecommends: typeof import('./src/views/home/component/HotRecommends.vue')['default']
    Recommends: typeof import('./src/views/category/components/Recommends.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubCategoryBread: typeof import('./src/views/category/components/SubCategoryBread.vue')['default']
    SubCategoryFilter: typeof import('./src/views/category/components/SubCategoryFilter.vue')['default']
    SubCategoryPage: typeof import('./src/views/category/SubCategoryPage.vue')['default']
    SubCategorySort: typeof import('./src/views/category/components/SubCategorySort.vue')['default']
    TopCategoryBread: typeof import('./src/views/category/components/TopCategoryBread.vue')['default']
    TopCategoryPage: typeof import('./src/views/category/TopCategoryPage.vue')['default']
    XtxBread: typeof import('./src/components/XtxBread.vue')['default']
    XtxBreadItem: typeof import('./src/components/XtxBreadItem.vue')['default']
    XtxCarousel: typeof import('./src/components/XtxCarousel.vue')['default']
    XtxCheckbox: typeof import('./src/components/XtxCheckbox.vue')['default']
    XtxFooter: typeof import('./src/components/XtxFooter.vue')['default']
    XtxHeader: typeof import('./src/components/XtxHeader.vue')['default']
    XtxHeaderNav: typeof import('./src/components/XtxHeaderNav.vue')['default']
    XtxHeaderSticky: typeof import('./src/components/XtxHeaderSticky.vue')['default']
    XtxInfiniteLoading: typeof import('./src/components/XtxInfiniteLoading.vue')['default']
    XtxLayout: typeof import('./src/components/XtxLayout.vue')['default']
    XtxMore: typeof import('./src/components/XtxMore.vue')['default']
    XtxSkeleton: typeof import('./src/components/XtxSkeleton.vue')['default']
    XtxTopNav: typeof import('./src/components/XtxTopNav.vue')['default']
  }
}

export {}
